# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-04 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('ltype', models.CharField(help_text='\u8bed\u8a00\u7c7b\u578b\uff0c\u4f8b\u5982 \u6cd5\u8bed / \u4fc4\u8bed', max_length=50)),
                ('difficulty', models.IntegerField(default=1, help_text='\u96be\u5ea6\u7b49\u7ea7\uff0c1-4')),
                ('utype', models.CharField(blank=True, help_text='\u8d44\u6e90\u5e73\u53f0\u7c7b\u578b\uff0c\u4f8b\u5982 bilibili / tiktok', max_length=50)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('image', models.CharField(blank=True, help_text='\u5c01\u9762\u56fe\u7247\u6587\u4ef6\u540d\u6216 URL', max_length=255)),
                ('time', models.CharField(blank=True, help_text='\u53d1\u5e03\u65f6\u95f4\u6587\u672c\uff0c\u4f8b\u5982 \xb7 2022-03-12', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(help_text='\u5b66\u4e60\u65f6\u95f4')),
                ('dura', models.IntegerField(help_text='\u5b66\u4e60\u65f6\u957f\uff0c\u5355\u4f4d\u6beb\u79d2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='web.Resource')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
