# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-05 01:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='\u5b66\u4e60\u8def\u5f84\u6807\u9898', max_length=255)),
                ('description', models.TextField(blank=True, help_text='\u63cf\u8ff0')),
                ('language', models.CharField(blank=True, help_text='\u76ee\u6807\u8bed\u8a00\uff0c\u4f8b\u5982 \u6cd5\u8bed / \u4fc4\u8bed', max_length=50)),
                ('target_level', models.CharField(blank=True, help_text='\u76ee\u6807\u6c34\u5e73\uff0c\u4f8b\u5982 A1 / B2', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text='\u662f\u5426\u516c\u5f00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='\u521b\u5efa\u8005', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='\u6392\u5e8f\u987a\u5e8f\uff0c\u6570\u5b57\u8d8a\u5c0f\u8d8a\u9760\u524d')),
                ('is_completed', models.BooleanField(default=False, help_text='\u662f\u5426\u5df2\u5b8c\u6210')),
                ('completed_at', models.DateTimeField(blank=True, help_text='\u5b8c\u6210\u65f6\u95f4', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web.LearningPath')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Resource')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
