# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-05 01:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_learningpath_learningpathitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='\u5e16\u5b50\u5185\u5bb9\uff08\u652f\u6301HTML\uff09')),
                ('image', models.CharField(blank=True, help_text='\u5e16\u5b50\u56fe\u7247URL\u6216\u8def\u5f84', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='\u53d1\u5e16\u7528\u6237', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
