# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-05 01:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0004_auto_20260305_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar_level', models.IntegerField(default=1, help_text='\u5b66\u8005\u7b49\u7ea7\uff1a1=\u521d\u7ea7\u5b66\u8005, 2=\u4e2d\u7ea7\u5b66\u8005, 3=\u9ad8\u7ea7\u5b66\u8005')),
                ('nickname', models.CharField(blank=True, help_text='\u6635\u79f0', max_length=50)),
                ('phone', models.CharField(blank=True, help_text='\u624b\u673a\u53f7', max_length=20)),
                ('avatar', models.CharField(blank=True, help_text='\u5934\u50cf', max_length=255)),
                ('sex', models.CharField(blank=True, help_text='\u6027\u522b\uff1aM=\u7537, F=\u5973', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
