# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-06 06:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupJoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.CharField(blank=True, help_text='Optional request message', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(help_text='Creator', on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, help_text='Group description'),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupid',
            field=models.CharField(help_text='Group ID', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Group name', max_length=255),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='content',
            field=models.TextField(help_text='Message content'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='description',
            field=models.TextField(blank=True, help_text='Description'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this path is public'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='language',
            field=models.CharField(blank=True, help_text='Target language, e.g. French / Russian', max_length=50),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='target_level',
            field=models.CharField(blank=True, help_text='Target level, e.g. A1 / B2', max_length=50),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='title',
            field=models.CharField(help_text='Path title', max_length=255),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='user',
            field=models.ForeignKey(help_text='Owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learningpathitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Completion timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='learningpathitem',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether this item is completed'),
        ),
        migrations.AlterField(
            model_name='learningpathitem',
            name='order',
            field=models.IntegerField(default=0, help_text='Order index; smaller means earlier'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Post content (HTML allowed)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, help_text='Post image URL or path', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(help_text='Author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='difficulty',
            field=models.IntegerField(default=1, help_text='Difficulty level, 1-4'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.CharField(blank=True, help_text='Cover image filename or URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='ltype',
            field=models.CharField(help_text='Language type, e.g. French / Russian', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='time',
            field=models.CharField(blank=True, help_text='Published time text, e.g. \xb7 2022-03-12', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='utype',
            field=models.CharField(blank=True, help_text='Platform type, e.g. bilibili / tiktok', max_length=50),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='dura',
            field=models.IntegerField(help_text='Study duration in milliseconds'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='time',
            field=models.DateTimeField(help_text='Study time'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, help_text='Avatar', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, help_text='Nickname', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='scholar_level',
            field=models.IntegerField(default=1, help_text='Scholar level: 1=Beginner, 2=Intermediate, 3=Advanced'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, help_text='Gender: M=Male, F=Female', max_length=1),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='web.Group'),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='web.Group'),
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_group_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='groupjoinrequest',
            unique_together=set([('group', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='groupinvite',
            unique_together=set([('group', 'invitee')]),
        ),
    ]
