# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-08 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20260306_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.CharField(blank=True, help_text='URL or external ID', max_length=500),
        ),
    ]
